# Generated by Django 5.2.7 on 2025-10-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jurusan', models.CharField(max_length=100)),
                ('angkatan', models.IntegerField()),
            ],
        ),
    ]
